### ISSUE TITLE
Limiting throughput of /v1/read-current-max-table-from-device

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/NetExplorerProxy#42]
A second IntegerProfile for limiting continuous throughput of /v1/read-current-max-table-from-device shall be added.
Configurable between 0 and maximum value of 20 requests a minute.

**Comment by kmohr-soprasteria** [comment]
429 is here also most suitable:

> [429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)
> The user has sent too many requests in a given amount of time ("rate limiting").
