### ISSUE TITLE
Harmonization of HTTP response codes

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/NetExplorerProxy#62]
The [response codes defined in the ApplicationPattern](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/HowToDefineErrorMessages/HowToDefineErrorMessages.md) shall be copied into the openAPI specification and become part of the implementation.

Check individual services for required changes to responseCodes; if it is necessary to define new individual responseCodes, these shall be added to the AppPattern documentation as well.

**Comment by kmohr-soprasteria** [comment]
Note: 
The individual services will retrieve data from MWDI and MATR.
Both applications do not yet support all the new harmonized responseCodes (for MWDI at least the next release specification has them already, but for MATR the spec still needs to be updated).

I.e. the new responseCodes will already be defined in the NEP spec, but them being actually returned will rely on the implementations of the related responseCodes in MATR and MWDI.

**Comment by kmohr-soprasteria** [comment]
![image](https://github.com/user-attachments/assets/ca627ecd-a900-4768-85b8-08c04b266655)

**Comment by kmohr-soprasteria** [comment]
remove the additional descriptions folder for responseCode overview from the spec
