### ISSUE TITLE
Clarification regarding storing the requestor details of /v1/read-current-mac-table-from-device

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/NetExplorerProxy#66]
As per the specification and the diagram https://github.com/openBackhaul/NetExplorerProxy/blob/development/spec/diagrams/002_ReadCurrentMacTableFromDevice.png , we have to store the requestor details in the in memory look up table. By storing them in the runtime memory of the application there is a possibility of data loss when NEP application goes down. Is this is fine ? or we can store this information in an application data file.

**Comment by kmohr-soprasteria** [comment]
When this service is called, the requestor needs the information within a short timeframe. So I guess when the NEP goes down, it is okay if the requestor information is lost.
(Also this service should not be called too frequently anyways.)

**Comment by PrathibaJee** [comment]
Thanks for the clarification. I will close this issue.
